version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - /home/rohan/server/memora-backend/prisma/dev.db:/usr/src/app/prisma/dev.db
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
